import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Sparkles, AlertTriangle, Lightbulb, ChevronRight, Info } from "lucide-react";
import { cn } from "@/lib/utils";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { useToast } from "@/hooks/use-toast";

interface Insight {
    id: string;
    type: "warning" | "suggestion" | "info";
    title: string;
    description: string;
    action?: string;
    project: string;
}

export default function AIInsightsPage() {
    const [insights, setInsights] = useState<Insight[]>([]);
    const [loading, setLoading] = useState(true);
    const { toast } = useToast();

    useEffect(() => {
        let mounted = true;
        const fetchInsights = async () => {
            setLoading(true);
            try {
                const res = await fetch("/api/copilot/insights");
                if (!res.ok) throw new Error("Failed to load insights");
                const data = await res.json();
                if (mounted) setInsights(data || []);
            } catch (e) {
                if (mounted) setInsights([]);
            } finally {
                if (mounted) setLoading(false);
            }
        };
        fetchInsights();
        return () => { mounted = false; };
    }, []);

    const getTypeConfig = (type: string) => {
        switch (type) {
            case "warning":
                return { class: "border-l-warning bg-warning/5", iconClass: "text-warning", icon: AlertTriangle };
            case "suggestion":
                return { class: "border-l-accent bg-accent/5", iconClass: "text-accent", icon: Lightbulb };
            default:
                return { class: "border-l-info bg-info/5", iconClass: "text-info", icon: Info };
        }
    };

    return (
        <DashboardLayout>
            <div className="space-y-4">
                <div className="flex items-center justify-between">
                    <div>
                        <h2 className="text-2xl font-semibold">AI Insights</h2>
                        <p className="text-sm text-muted-foreground">All recommendations generated by the Copilot</p>
                    </div>
                    <div>
                        <Badge variant="outline" className="text-sm">{loading ? "..." : insights.length}</Badge>
                    </div>
                </div>

                <div className="grid gap-4">
                    {loading ? (
                        <div>Loading...</div>
                    ) : (
                        insights.map((insight) => {
                            const config = getTypeConfig(insight.type);
                            const Icon = config.icon as any;
                            return (
                                <div key={insight.id} className={cn("rounded-lg border-l-4 p-4 bg-card border border-border/50", config.class)}>
                                    <div className="flex items-start gap-3">
                                        <Icon className={cn("mt-0.5 h-5 w-5 flex-shrink-0", config.iconClass)} />
                                        <div className="flex-1 space-y-2">
                                            <div>
                                                <h4 className="text-sm font-medium text-foreground">{insight.title}</h4>
                                                <p className="mt-1 text-xs text-muted-foreground">{insight.description}</p>
                                            </div>
                                            <div className="flex items-center justify-between">
                                                <span className="text-xs text-muted-foreground">{insight.project}</span>
                                                <div className="flex items-center gap-2">
                                                    {insight.action && (
                                                        <Button variant="ghost" size="sm" className="h-7 text-xs text-accent hover:text-accent">
                                                            {insight.action}
                                                            <ChevronRight className="ml-1 h-3 w-3" />
                                                        </Button>
                                                    )}
                                                    <Button
                                                        variant="secondary"
                                                        size="sm"
                                                        className="h-7 text-xs"
                                                        onClick={async () => {
                                                            try {
                                                                const res = await fetch("/api/copilot/apply-insight", {
                                                                    method: "POST",
                                                                    headers: { "Content-Type": "application/json" },
                                                                    body: JSON.stringify(insight),
                                                                });
                                                                if (!res.ok) throw new Error("Failed to apply insight");
                                                                const json = await res.json();
                                                                setInsights((s) => s.filter((i) => i.id !== insight.id));
                                                                toast({ title: "Insight applied", description: `Saved as QA insight (#${json.id})` });
                                                            } catch (e) {
                                                                toast({ title: "Error", description: e instanceof Error ? e.message : "Failed to apply insight", variant: "destructive" });
                                                            }
                                                        }}
                                                    >
                                                        Approve
                                                    </Button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            );
                        })
                    )}
                </div>
            </div>
        </DashboardLayout>
    );
}
